fix gamma handling for GigE cameras
magazino/pylon_camera pull request #9
Opened 2017-02-07 10:52 UTC by beetleskin

When connecting to a GigE camera (e.g. aca1920-50gc), the node crashes with "Error while accessing Gamma in PylonCameraImpl<CameraTraitT>": For some camera types, the Gamma settings might not available to the interface on startup, as they are handled automatically by the camera itself (Auto Gamma). This was already partly handled for some gamma-related function calls, but not for all of them. This fix adds the missing checks. The behaviour is slightly changed: If the gamma is not set via user, gamma remains in auto mode (i.e. controlled by the camera). Once the user tries to set a gamma value, the gamma mode switches to user.

2017-02-09 20:43 UTC, mgrrx requested changes

2017-02-09 20:43 UTC, mgrrx commented on include/pylon_camera/internal/impl/pylon_camera_gige.hpp
> +        if( !GenApi::IsAvailable(cam_->Gamma)) {
Could you please re-indent these lines to follow the style guide

2017-02-13 11:55 UTC, beetleskin commented
@mgrrx fixed style and squashed it to the commit.

2017-02-15 14:30 UTC, merged

2017-02-15 14:56 UTC, marceldebout commented
@beetleskin I reviewed your PR, made some adaptions and merged it. Could you please try this out with your GigE color camera and provide me feedback if this solution worked for your case?

2017-02-16 14:05 UTC, beetleskin commented
@marceldebout Works like a charm, thanks a lot for the quick merge!